### ISSUE TITLE
"getAllOrders" and "getAllActiveOrders" implementation

### ISSUE THREAD

**Issue by bmsrangel** [Vikirito1/Quiosque#39]
Reviewing the code for these two methods, I noticed that maybe we have implemented them "incorrectly". Actually, it's not wrong, but maybe we did more than the necessary.

In a first moment, the "getAllActiveOrders" should only return the list of active orders, used in HomeScreen to define which tables should be red or green. This means that at this point the list of products of each order is not necessary.

This list should be retrieved, then, in the TableOrder screen, which opens when a table is tapped.

So, should we change the behavior of these methods and create a new one to get the product list of the selected table?

**Comment by Vikirito1** [comment]
Sure, this is the correct implementation, right? Creating Method to specific actions, not more, not less.

**Comment by bmsrangel** [comment]
This change was duly implemented and both methods no longer return a list of products, as expected.
