### ISSUE TITLE
Set proper application name

### ISSUE THREAD

**Issue by bmsrangel** [Vikirito1/Quiosque#68]
Is it going to be "Quiosque"? Should we change it by "Kioske" following the customer's name? Or maybe "Tô na praia"?

<img width="712" alt="image" src="https://user-images.githubusercontent.com/39227201/146628346-568aac83-1335-460c-b179-36d497d4ee79.png">

**Comment by Vikirito1** [comment]
we can keep a basic project called quisque and make a copy for this client with a proper name "Kiosque Tô na Praia" and also de logo as the app icon.

**Comment by bmsrangel** [comment]
Good! I'll make the change and make a PR closing this issue
